### ISSUE TITLE
How do I download this?

### ISSUE THREAD

**Issue by GroovinChip** [ShadySquirrel/ViPER4Android#10]
Sorry if it seems like a silly question but I don't see a download link anywhere on the readme

**Comment by ShadySquirrel** [comment]
Under ['Releases'](https://github.com/ShadySquirrel/ViPER4Android/releases) tab, if you want Materialized version, or directly from Magisk Manager if you want standard app.

**Comment by GroovinChip** [comment]
Thank you!
