### ISSUE TITLE
safty net disable

### ISSUE THREAD

**Issue by shanishkag** [ShadySquirrel/ViPER4Android#11]
if i install this module in my s7 edge sm-g935fd magisk v14 it will disable the safty net. uninstall module safty net bypass and start working nomal

**Comment by ShadySquirrel** [comment]
Please fill the report properly.

**Comment by shanishkag** [comment]
with this module failed to bypass safty net in magisk v14
if i remove modul magisk bypass safty net as nomal

**Comment by ShadySquirrel** [comment]
No proper log after 2 days, closing and locking.
