### ISSUE TITLE
Processing: "no"

### ISSUE THREAD

**Issue by Manu99it** [ShadySquirrel/ViPER4Android#13]
Device: Xiaomi Mi 5 gemini
ROM: LineageOS 14.1 build 07/11 (I will update lately maybe)
Tried with various player: the status of driver is ok, but it stay always in not processing. I've also looked at similar issues but from what I've seen there isn't a specific solution so I'm opening this

**Comment by ShadySquirrel** [comment]
No need for log files, but can you at least upload audio_effects.conf files?

**Comment by Manu99it** [comment]
[audio_effects.zip](https://github.com/ShadySquirrel/ViPER4Android/files/1540751/audio_effects.zip)
Yeah sure excuse me

**Comment by ShadySquirrel** [comment]
Like I thought... You have duplicated v4a entries in your config:
```
libraries {
  v4a_fx {
    path /system/lib/soundfx/libv4a_fx_ics.so
  }
  v4a_fx {
    path /system/lib/soundfx/libv4a_fx_ics.so
  }
```
You had any other sound mods installed previously? Uninstall everything sound related and reinstall my module.

**Comment by Manu99it** [comment]
No, I hadn't other mods from when I've done a clean flash, just your. I will uninstall and reinstall it however. Can I also edit manually the audio config however removing duplicated lines?

**Comment by ShadySquirrel** [comment]
Funny, that means installer modded that file twice... which it shouldn't do. I'll check the script later on my device...

You can try editing one found in module directory (/magisk/viper4android/...), just make sure you don't have any syntax errors and don't forget to reboot after that.

You have to remove duplicated entries under:
```
libraries {
  v4a_fx {
    path /system/lib/soundfx/libv4a_fx_ics.so
  }
  v4a_fx {
    path /system/lib/soundfx/libv4a_fx_ics.so
  }
...
```
and
```
effects {
  v4a_standard_fx {
    library v4a_fx
    uuid 41d3c987-e6cf-11e3-a88a-11aba5d5c51b
  }
  v4a_standard_fx 
    library v4a_fx
    uuid 41d3c987-e6cf-11e3-a88a-11aba5d5c51b
  }
...
}
```

**Comment by Manu99it** [comment]
Ok, done. But still not processing :(

**Comment by ShadySquirrel** [comment]
Can you check was config file change permanent? I've noticed it doesn't play nice when you edit mounted files - that's why I've told you to uninstall my module and reinstall.

**Comment by Manu99it** [comment]
I've already checked, the modification is permanent

**Comment by ShadySquirrel** [comment]
Ok, now I'm gonna need to see logs (full kernel log, logcat etc.) and ask you to check if V4A is working in Compatibility mode.
Have you disabled AudioFX by chance?

**Comment by Manu99it** [comment]
[2017-12-09_17.19.zip](https://github.com/ShadySquirrel/ViPER4Android/files/1544813/2017-12-09_17.19.zip)
It doesn't work in compatibility mode either. And yes, AudioFX is disabled (and also I tried to keep it freezed)

**Comment by ShadySquirrel** [comment]
I'm not sure V4A is even working with Spotify at all (it's not available in my country so I can't test it). About other players, looks like you have some other audio effects available on your device (PowerAMP has its own DSP as far as I remember, it will work with V4A only in compatibility mode) so it's messing around with V4A.
You can try Settings-> Sound -> Sound effects and see what it offers... If not, keep it in compatibility.

**Comment by Manu99it** [comment]
Well I've already said that I've tried with others players (and however I've used PowerAmp also with viper in past, obviously with direct control audio option unchecked). However now every player now works in compatibility, Spotify also. But I would like use viper4droid with the driver. I've flashed your module because I early had to keep selinux in permissive, while with your magisk module I can keep it in enforced

**Comment by ShadySquirrel** [comment]
If V4A works only in compatibility, it means that it probably has a conflict with some other audio lib - and since my device too is on LOS (kiwi), I'm puzzled which one can that be - I'm *guessing* Dirac, because I see that your device has Dirac sound support:
```
12-09 17:16:38.213 I/ViPER4Android( 4099): Found 20 effects
12-09 17:16:38.213 I/ViPER4Android( 4099): [1], DiracSound, Dirac Audio Effect
12-09 17:16:38.213 I/ViPER4Android( 4099): [2], Volume listener for notification, Qualcomm Technologies Inc
12-09 17:16:38.213 I/ViPER4Android( 4099): [3], Volume listener for voice call, Qualcomm Technologies Inc
12-09 17:16:38.213 I/ViPER4Android( 4099): [4], Volume listener for alarm, Qualcomm Technologies Inc
12-09 17:16:38.213 I/ViPER4Android( 4099): [5], Volume listener for ring, Qualcomm Technologies Inc
12-09 17:16:38.213 I/ViPER4Android( 4099): [6], Volume listener for Music, Qualcomm Technologies Inc.
12-09 17:16:38.213 I/ViPER4Android( 4099): [7], Noise Suppression, Qualcomm Fluence
12-09 17:16:38.213 I/ViPER4Android( 4099): [8], Acoustic Echo Canceler, Qualcomm Fluence
12-09 17:16:38.213 I/ViPER4Android( 4099): [9], Visualizer, The Android Open Source Project
12-09 17:16:38.213 I/ViPER4Android( 4099): [10], Qualcomm Technologies Insert Preset Reverb, Qualcomm Technologies, Inc.
12-09 17:16:38.213 I/ViPER4Android( 4099): [11], Qualcomm Technologies Auxiliary Preset Reverb, Qualcomm Technologies, Inc.
12-09 17:16:38.213 I/ViPER4Android( 4099): [12], Qualcomm Technologies Insert Environmental Reverb, Qualcomm Technologies, Inc.
12-09 17:16:38.213 I/ViPER4Android( 4099): [13], Qualcomm Technologies Auxiliary Environmental Reverb, Qualcomm Technologies, Inc.
12-09 17:16:38.213 I/ViPER4Android( 4099): [14], Equalizer, NXP Software Ltd.
12-09 17:16:38.213 I/ViPER4Android( 4099): [15], Qualcomm Technologies Virtualizer, Qualcomm Technologies, Inc.
12-09 17:16:38.213 I/ViPER4Android( 4099): [16], Qualcomm Technologies Bass Boost, Qualcomm Technologies, Inc.
12-09 17:16:38.213 I/ViPER4Android( 4099): [17], Loudness Enhancer, The Android Open Source Project
12-09 17:16:38.213 I/ViPER4Android( 4099): [18], Multichannel Downmix To Stereo, The Android Open Source Project
12-09 17:16:38.213 I/ViPER4Android( 4099): [19], Volume, NXP Software Ltd.
12-09 17:16:38.213 I/ViPER4Android( 4099): [20], ViPER4Android [2.5.0.4], ViPER.WYF
```
And knowing how people with OnePlus3/3T have issues with Dirac & V4A, that's maybe a direction we should investigate further... or bother people behind V4A to fix.

**Comment by Manu99it** [comment]
Oh I see. Well I know that on Aosp Extended your module on my same device works. So it's strange, maybe is a ROM fault. Anyway, thanks for your time!

**Comment by ShadySquirrel** [comment]
Check if you have `Dirac*` folders in `/system/app` and `/system/priv-app` as described in #5. Other than that, if it works on one ROM but not on other, well, it probably is some difference between device trees problematic, as I've experienced earlier in #8, when V4A stopped working between two updates.

**Comment by Manu99it** [comment]
I don't have Dirac. If the problem is the same of #8 I will try when I flash a new update or another rom and I will verify
