### ISSUE TITLE
No processing Magisk v15.1

### ISSUE THREAD

**Issue by BlackTangerine9** [ShadySquirrel/ViPER4Android#16]
Module and Magisk version

      Viper4android FX for Magisk v15. Driver - 2.5.0.4. Magisk v15.1

Phone model, OS and version,

     Samsung S6 Edge SM-G925F, android stock 7.0.

List of installed modules

     V4A (your module), injected YouTube Background Playback Vanced - black themed Magisk Repo, Busybox for Android NDK

Is any other sound mod installed?

     No, although I have been installing and uninstalling multiple times. (Should be clear from duplicate install).

Logs - logcat, FULL kmsg, Magisk log,
audio_effects.conf file from /system/etc, /system/vendor/etc, or wherever is your audio effects configuration

 https://pastebin.com/cy19P7x9
 https://drive.google.com/folderview?id=1xa22a91BDnKaeSLBHWe1w1m14fR51-Y4

     No kmsg atm, can do it asap if required

A description of an issue or debugging info you may have or find usable.

          Nothing really out of the ordinary, just installed the module and wasn't able to get it to work in either compatible or normal mode. I know about the Deep_fix - something if that name but it didn't help

I had the same problem with Magisk 14 but for some reason one day it magically worked

Please let me know if you require any more extra information, it's probably just me being stupid that's causing this error but I honestly can't figure it out. Thank you!

**Comment by ShadySquirrel** [comment]
Can you close V4A app (stop it from Settings->App and swipe from Overview/Recents) and reopen it and grab logcat then?

I can see that V4A is processing, but I'm afraid it's conflicting with Samsung's internal workings or maybe something similar. Which player are you using?

**Comment by BlackTangerine9** [comment]
Hey, thank you for the reply

https://drive.google.com/file/d/12CED24RfaHt9YunmRzHyqswzEvtJLrnj/view?usp=drivesdk

I feel a bit stupid, but I'm using Samsung's Music Player (pre-installed into the phone). The thing is, I've made sure to disable or at least turn off all music FX from samsung. 

Regards

**Comment by ShadySquirrel** [comment]
All is OK. Can you try with different player? I think that Sammy's default player has a mind of its own :D

**Comment by BlackTangerine9** [comment]
Hey

So I wasn't able to get it to work unfortunately (I used pi player and gave up haha).

Anyway, I appreciate the attempt and the work you've done. If I find a fix (I just think it's the version of viper in general causing the problem) I'll let you know.

Regards

**Comment by y2klol** [comment]
I am having similar problems. I have tried shuttle+, spotify and poweramp. I am unsure on how to get the logcat.

**Comment by BlackTangerine9** [comment]
Hey

I used playstore and grabbed any logcat app. After running the app, I opened V4A and played music, after, I checked if processing changed - it didn't. Then try to save the log and upload to Drive or pastebin.

I uninstalled YouTube Vanced but that didn't resolve it either. Dev suggested removing all audio mods before turning on V4A.

Regards

**Comment by ShadySquirrel** [comment]
Samsung devices are usually a black sheep these days... If V4A is reporting that everything is ok, but processing doesn't work, check configs (should be no duplicate V4A entries), try compatibility mode (and reboot), disable all audio effects you can find, switch players etc. Library is closed source so I can't do much about device compatibility, just provide a way to keep the app working and your system clean.

Can you set default audio effects in sound settings?

**Comment by seaskimmer** [comment]
Same issue. S6e SM-G925F running stock 7.0. Poweramp music player.

Previously with v14, the fix I found to work was to move /magisk/v4a/system/etc/audio_effects.conf to /magisk/v4a/system/vendor/etc/audio_effects.conf then reboot. However, this does not seem to work with v15.

Speaking of which, is it safe to uninstall v15 and downgrade to v14?

**Comment by y2klol** [comment]
I got it to work! What I did was deleted the module, flashed the official V4A module (using twrp) which didn't work but I did press the option to "uninstall driver" then deleted it. I then reinstalled this module from magisk and it started working again.

**Comment by ShadySquirrel** [comment]
@seaskimmer installer should modify that one found in /system/vendor/etc, no need to modify it manually... But yeah, your issue was with PowerAMP and it's own sound-processing. Compatibility mode is the key there.

@y2klol you probably had bad configuration, that's why I've included the steps 'all audio_effect.conf' files in 'Issues' part of README. I'm trying to find a way to check if configuration was already altered somehow, but so far no good enough results.

**Comment by stonerl** [comment]
I do have the same problem. Everything is fine except that it never processes any sound. Testet with Spotify, uPod, Newpipe and Firefox.

My Setup: Oneplus3 A3003 with latest Firmware & Modem (from OS 5.0.1) running LineageOS 14.1 (20180105) official and Magisk 15.3.

If you need any logs let me know.

**Comment by ShadySquirrel** [comment]
It's known issue with OP devices.

Can you try something for me? People who tested my module don't have OPs, I have Huawei and older LG and it worked there without this change, but someone mentioned that this fixed V4A for their OnePlus:

Add this line to module's post-fs-data.sh:
`magiskpolicy  --live "allow hal_audio_default hal_audio_default process { execmem }"`

And reboot.

File path: `/magisk/viper4android/post-fs-data.sh'

**Comment by ShadySquirrel** [comment]
Please try module version 5.1. I got users reporting success with change mentioned above. If problems persist, reopen this issue

**Comment by stonerl** [comment]
@ShadySquirrel Didn't solve it for me. I tried all available Viper Modules for Magisk so far, but non of them processed any audio. Seems to be a huge problem with 1+ devices it seems.

**Comment by ShadySquirrel** [comment]
Yeah, if SEPolicy isn't an issue, Dirac is wreaking havoc with V4A... But I'm not sure if Lineage is including Dirac?
