### ISSUE TITLE
No audio processing on 1+5 8.0

### ISSUE THREAD

**Issue by DvLAx3l** [ShadySquirrel/ViPER4Android#17]
I'm using ur almost (for that issue 🤣 ) perfect Magisk module from the 1st release.
I've updated the device to the official oreo rom and the module dosn't work anymore, I've tryed also the materialized module but nothing, it doesn't work. Tell me what u need from my phone to try somenthing 😝. 

Device: OnePlus 5
Android version: OOS 5.0 (8.0) + Magisk 15.2

**Comment by ShadySquirrel** [comment]
There is all info in the README file. But seeing how you're on OnePlus, I'd say it's a device quirk because I already had reports and issues because of Dirac.

**Comment by DvLAx3l** [comment]
Ok so need logcat etc. I'll do it, my bad, didn't read it.

**Comment by DvLAx3l** [comment]
Man thanks for ur work, untill I'm out for work I can't dedicate too much time to achieve all the logs, so I'll do it when I can, anyway just to let u know, I've tried another module from the official repo and it works, probably for the audiomod library that install... So, I'll keep u update.

**Comment by DvLAx3l** [comment]
I'll close the issue, i'm sending moving and didn't have time. sry for the waste of time bro, anyway if i'll have time i'll let u know

**Comment by ShadySquirrel** [comment]
Someone on XDA suggested to me to add one more SEPolicy rule, which seem to fix issues with OP5. I'll push a zip in a day or two, just to finish some other work first.

**Comment by ShadySquirrel** [comment]
Someone on XDA suggested to me to add one more SEPolicy rule, which seem to fix issues with OP5. I'll push a zip in a day or two, just to finish some other work first.

**Comment by DvLAx3l** [comment]
Thanks again! I'll try when it's ready! 😄

**Comment by ShadySquirrel** [comment]
@DvLAx3l I can't find enough time to push this, and I need more OnePlus users testing it. Can you check my [last comment](https://github.com/ShadySquirrel/ViPER4Android/issues/16#issuecomment-357464398) on issue #16 ?

**Comment by DvLAx3l** [comment]
Done! Checked, i add that line to the post-fs-data.sh now everything is working! Congratulation! U solved the issue without any log or test, thanks!

**Comment by ShadySquirrel** [comment]
Well, somebody else solved it for me, lol, and sent me message on XDA. I can't find them here now to give them proper credit.

That's why you kids do pull requests...
