### ISSUE TITLE
No driver installed error. I/O error when trying to install driver

### ISSUE THREAD

**Issue by kindrich** [ShadySquirrel/ViPER4Android#18]
Sorry it's been a while since I last used V4A. When I open the V4A FX app, I get the error:
"In order to use ViPER4Android, you need to install/update the V4A driver" and am prompted to install the driver. When I select install, I get the error "Driver install failed: I/O error. Please reboot and try again." I've rebooted and tried again several times to no avail.

Here's my setup and what I've done to install your module:
- Stock 8.1 ROM
- Installed Magisk using TWRP booted from RAM
- Installed patched stock kernel to use Android Pay using fastboot
- Install your module
And that's it! Is there anything else I need to install/modify?
Thanks for the module and your support!

Details:
- Module version: 5.1
- Magisk version: 15.3
- Phone: Pixel XL 8.1 Jan 2018 SPL
- No other module installed
- No other sound mod installed
- Contents of /system/etc/audio_effects.conf is attached.
[audio_effects.conf.txt](https://github.com/ShadySquirrel/ViPER4Android/files/1632734/audio_effects.conf.txt)

**Comment by ShadySquirrel** [comment]
Can you try with Materialised module version?

**Comment by kindrich** [comment]
I've tried the Materialised as well and still get the same error.

Do I neet to worry about changing SE Enforcing to SE Permissive?

**Comment by ShadySquirrel** [comment]
No need for that, if Magisk's policy injection is working good, there should be no reason to use permissive sepolicy with my module... Unless there is something Pixel-specific, like OnePlus devices have their thing. But, just to be sure... Can you try running with SEPolicy off and grab me a full (`adb logcat -b all`) logcat?

**Comment by kindrich** [comment]
[logcat.txt.zip](https://github.com/ShadySquirrel/ViPER4Android/files/1633019/logcat.txt.zip)
Here you go!

Events related to ViPER4Android are around 13:10 and towards the end of the file.

**Comment by ShadySquirrel** [comment]
Is this with sepolicy enforcing or permissive? Also, please, do the same with Materialized.

Can you check are there any other audio_effects.conf files? For example in /vendor/etc and similar folders.

**Comment by kindrich** [comment]
I did:
`setenforce 0` and `getenforce` to set and verify that SE is Permissive.

Yes, there's a `audio_effects.xml` in `/vendor/etc` folder. Should I copy the ViPER4Android related lines from the file in `/system/etc` to the file in `/vendor/etc
[logcat_materialized.txt.zip](https://github.com/ShadySquirrel/ViPER4Android/files/1633056/logcat_materialized.txt.zip)
`?

**Comment by ShadySquirrel** [comment]
Don't do that, looks like formats are different (conf vs xml).
Can you upload that file from /vendor/etc?

**Comment by kindrich** [comment]
Here you go!
[audio_effects.xml.txt](https://github.com/ShadySquirrel/ViPER4Android/files/1633063/audio_effects.xml.txt)

Even though the formats are different, it's pretty clear where the content from the .conf file should go in the .xml (with the modification to match the rest of the .xml file of course)

**Comment by ShadySquirrel** [comment]
Holly cow Google, what the hell...

Okay, can you copy that file I've upoaded to `/magisk/viper4android/vendor/etc/audio_effects.xml` (or `/magisk/viper4android_material/vendor/etc/audio_effects.xml` for materialised version, and reboot after?

[audio_effects.xml.gz](https://github.com/ShadySquirrel/ViPER4Android/files/1633077/audio_effects.xml.gz)

Basically, I've added
`<library name="v4a_fx" path="/system/lib/soundfx/libv4a_fx_ics.so"/>` to the start of <libraries> block
and
`<effect name="v4a_standard_fx" library="v4a_fx" uuid="41d3c987-e6cf-11e3-a88a-11aba5d5c51b"/>` to the start of <effects> block
which should do the trick.

**Comment by kindrich** [comment]
I copied and pasted your file to /vendor/etc, changed the permission to 644 and rebooted. Unfortunately that still doesn't work T_T. There might be another one of these audio effects config file somewhere. I'll keep looking and get back to you.

The last time I used V4A was on the Nexus 6P. I guess long gone is the day when every mod just worked on Google devices.

**Comment by ShadySquirrel** [comment]
No no no, don't edit vendor partition directly. Do it the Magisk way, it should take care of everything if you put that file in right place.

Is there any change? From "drivers missing" towards "status abnormal" at least?

Pull logs with that file active, I'm really intrigued now.

**Comment by kindrich** [comment]
Whoops sorry - I didn't know what you meant by the Magisk-way. Figured it out (duh!) and did it the correct way.

The driver status does indeed say "abnormal" with this file active.
[logcat_xml_mod.txt](https://github.com/ShadySquirrel/ViPER4Android/files/1633169/logcat_xml_mod.txt)


Logcat attached.

**Comment by ShadySquirrel** [comment]
That's something, a progress, lol.

My guess is that sepolicy is messing around, even when it's in permissive. I'm seeing bunch of denials here, so it may take some time for me to find out what it doesn't like. I'm guessing this:
`auditd  : type=1400 audit(0.0:19): avc: denied { search } for comm="audio@2.0-servi" name="audio" dev="sda35" ino=262212 scontext=u:r:hal_audio_default:s0 tcontext=u:object_r:audio_data_file:s0 tclass=dir permissive=0`

I'll try to find more about this one.

**Comment by k0u5h1k** [comment]
I have same issue with Mi A1 android one 8.0 rom

**Comment by ShadySquirrel** [comment]
Same rules, device info and logs, but please lets keep this thread clean, post to your own issue.

**Comment by kindrich** [comment]
I've checked and there's no duplicated entries in /system/etc/audio_effect.conf.

BTW, your module works perfectly on my OnePlus 5T running OxygenOS Oreo 8.0 Open Beta 2.

**Comment by ShadySquirrel** [comment]
Yeah, latest fix for sepolicy was included ater some OP users reported it worked for them.

Can you try one more thing? 
Add `search` to the `magiskpolicy --live "allow hal_audio_default hal_audio_default process { execmem }"` line in `/magisk/viper4android/post-fs-data.sh`, and reboot.

Line should look like this after that:
`magiskpolicy --live "allow hal_audio_default hal_audio_default process { search execmem }`

**Comment by kindrich** [comment]
Sorry but that doesn't work.

Thanks for not giving up!

**Comment by ShadySquirrel** [comment]
Okay, this is last idea for today.

You still have that audio_conf.xml file I told you to add to module path?

Remove whole `/system/lib/soundfx/` path from the v4a line in first segment, save and reboot.

**Comment by kindrich** [comment]
You meant the `/magisk/viper4android/system/vendor/audio_effects.xml` right?

I've edited it and now the first segment looks like this:

`<libraries>
        <library name="v4a_fx" path="libv4a_fx_ics.so"/>
        <library name="bundle" path="libbundlewrapper.so"/>
        <library name="reverb" path="libreverbwrapper.so"/>
        <library name="visualizer_sw" path="libvisualizer.so"/>
        <library name="visualizer_hw" path="libqcomvisualizer.so"/>
        <library name="fmas" path="libfmas.so"/>
        <library name="loudness_enhancer" path="libldnhncr.so"/>
        <library name="proxy" path="libeffectproxy.so"/>
        <library name="offload_bundle" path="libqcompostprocbundle.so"/>
        <library name="qcom_pre_processing" path="libqcomvoiceprocessing.so"/>
        <library name="volume_listener" path="libvolumelistener.so"/>
    </libraries>
`

After rebooting, the V4A app no longer complained about the missing driver anymore, but the driver status still shows as "Abnormal."

But then for the heck of it I tried setting SEPolicy to Permissive and IT WORKED!

**Comment by ShadySquirrel** [comment]
Small victory! OK, so far we've figured out that /vendor/etc/audio_effects.xml is primary one and it doesn't like full paths for library names.

Now, can you grab one more logcat for me (with `adb logcat -b al`, like before)?

I need to check what sepolicy is making that fuss.

**Comment by kindrich** [comment]
Here you go!

I opened the V4A with SEPolicy = Enforcing (showing Driver Status = Abnormal), then `setenforce 0` and opened the V4A FX app again (Driver Status =Enabled).

**Comment by kindrich** [comment]
Whoops forgot to attach!
[logcat_20180117.txt.zip](https://github.com/ShadySquirrel/ViPER4Android/files/1641026/logcat_20180117.txt.zip)

**Comment by ShadySquirrel** [comment]
I'm seeing these lines again:
```
01-17 15:45:47.640  3896  3896 I auditd  : type=1400 audit(0.0:204): avc: denied { execute } for comm="HwBinder:3881_3" path=2F6465762F7A65726F202864656C6574656429 dev="tmpfs" ino=47526 scontext=u:r:hal_audio_default:s0 tcontext=u:object_r:hal_audio_default_tmpfs:s0 tclass=file permissive=1
01-17 15:45:47.640  3896  3896 I HwBinder:3881_3: type=1400 audit(0.0:204): avc: denied { execute } for path=2F6465762F7A65726F202864656C6574656429 dev="tmpfs" ino=47526 scontext=u:r:hal_audio_default:s0 tcontext=u:object_r:hal_audio_default_tmpfs:s0 tclass=file permissive=1
```
Looks like it needs to be patched for exec permissions, too, not only execmem.

Ok, I need you to try this with `post-data-fs` file:
Change line
`magiskpolicy --live "allow hal_audio_default hal_audio_default process { search execmem }"`
back to 
`magiskpolicy --live "allow hal_audio_default hal_audio_default process { execmem }"`
And add line:
`magiskpolicy --live "allow hal_audio_default hal_audio_default_tmpfs file  { execute }"`

Ofc, save & reboot.

**Comment by ShadySquirrel** [comment]
Hey, did you have any success with sepolicy change?

**Comment by kindrich** [comment]
Sorry work has been busy these past 2 days. I'll try this later today and get back to you

**Comment by ShadySquirrel** [comment]
I'm not sure why github hasn't published my response, but ok.

Don't rush yourself, when you have time. I had similar issue in the meantime with Mi A1 and sepolicy you should test fixed it, so as soon as you answer me is it working for you I'll publish it.

**Comment by kindrich** [comment]
Editing the post-data-fs did it! V4A works as expected now without any error, driver status is Normal even when SEPolicy = Enforcing!

Thank you so much for your patience and persistence!

**Comment by ShadySquirrel** [comment]
You're welcome, thank you for testing and providing necessary logs :) Because those sepolicy rules fix V4A on multiple Oreo devices, I'll update module later tonight, with that and xml config support.

Again, thank you for testing this!

Marking as solved and closing.

**Comment by ShadySquirrel** [comment]
Hey @kindrich, can you try prerelease v6? I'd really like to get some feedback from more A/B users.

**Comment by kindrich** [comment]
Unfortunately I dropped my Pixel XL and dropped the screen. I'm currently using my back up phone the Essential PH-1. Would you still be interested in feedback from that device?

**Comment by ShadySquirrel** [comment]
You're using EP as a backup? Damn I must step my game up, my backup is 7y old Samsung :)

Jokes aside, if it's using same A/B layout and Oreo, it would be really nice getting info on that.

**Comment by kindrich** [comment]
LOL there's a reason it's a backup phone despite being newer than the Pixel XL. The hardware is stunning but the software is laggy as hell. I got a good deal from Craigslist :-).
My EP is running Oreo Beta 3 and I'm already using your v5.2 without any issue. How do I get the pre-release v6?

**Comment by ShadySquirrel** [comment]
You can grab (almost all) of releases from ["Releases"](https://github.com/ShadySquirrel/ViPER4Android/releases) project page. Just remove previous module before testing, to make sure no residue from previous installation is left - this version has new mechanism for config file detection and is automatically replacing meddling audio effect apps.

**Comment by coolhandz** [comment]
I went ahead and tried your beta release (v6) on my Pixel XL w/ BenzoRom.  After disabling SELinux and rebooting it seems to be working fine now.

**Comment by ShadySquirrel** [comment]
It should work with enforcing sepolicy.

Have you changed sepolicy status in v4a or within something like SEPolicy changer? If it's in V4A, that's for current session only.

**Comment by coolhandz** [comment]
then disregard.  did it in V4A itself.  After reboot though it started working.  strange.

**Comment by ShadySquirrel** [comment]
There are some quirks with magisk lately, I got few reports recently about module not working at all with configurations it should, and after seeing logs, magisk wasn't even mounting all module files, just folder paths. With my device, while it was encrypted, it didn't inject sepolicy unless I clear caches; really weird stuff...

**Comment by coolhandz** [comment]
OK.  So I installed .zip after download and rebooted the phone.  After boot I checked driver status and noticed everything working, but Processing said 'no' and no effects were working.  Then I disabled SELinux and still nothing.  After another reboot, effects are working, but you can't check driver status.  It won't open. Period.  Rebooted again and same deal.  Effects work, but can't check driver.

**Comment by ShadySquirrel** [comment]
You aren't in Compatible mode by any chance?

**Comment by coolhandz** [comment]
Not in compatible mode.  Will try materialised when i go back to work in about half an hour.

**Comment by kindrich** [comment]
I can confirm that v6 works just fine on Oreo 8.0. Perhaps 8.1 messes things up somehow?
Essential will release a 8.1 beta soon. I'll report back whether the module still works.

**Comment by ShadySquirrel** [comment]
Thanks, it would help a lot. 

It should work just fine, not much has changed between revisions, but who knows what Google did. V4A app and lib also need a good rewrite, plus there are some issues with Magisk lately which I couldn't decipher because, TBH, most people suck at providing logs and feedback
