### ISSUE TITLE
Enabled: Yes, Processing: No

### ISSUE THREAD

**Issue by SaamyoHalder** [ShadySquirrel/ViPER4Android#20]
Hello there Mr. ShadySquirrel!

I'm using a OnePlus 3T running OOS 5.0.1 based on Oreo 8.0

I've been using your V4A module since this device had Nougat, and never experienced any issues until the last OTA update I was pushed by OnePlus. Earlier, the processing used to say "Yes", but now it only says "No" no matter what I do. Earlier, I used to use a SELinux permissive script for Magisk, but something about that script broke with Magisk 15.x, and now the app "Root Validator" which I used for checking the SELinux state, returns an unknown state. I have no idea what to do now. Please help!

**Comment by ShadySquirrel** [comment]
Have you updated the module? I've pushed new version with some OnePlus specific sepolicy patches yesterday, haven't got time to upload materialised version release yet but normal one is available on magisk repo.

**Comment by SaamyoHalder** [comment]
I have the v5.1 module running, and when I use it with SELinux enforcing, it says Status: Abnormal. When I use SELinux mode changer to change to permissive, it then says "Processing: Yes" when the audio is NOT playing. As soon as the audio starts to play (via Bluetooth), it says "Processing: No".

**Comment by SaamyoHalder** [comment]
Update: V4A works for earphones/headphones using aux, but not for Bluetooth. Now this is something I've never had happen before :(

**Comment by SaamyoHalder** [comment]
Update 2: It's Mysteriously working for Bluetooth now too! This is weird...

**Comment by SaamyoHalder** [comment]
Update 3: It just randomly stopped working again 😔
I'm extremely sorry if I'm increasing the thread count for no reason, but this issue is boggling my mind! I tried to set SELinux to enforcing then again to permissive to check whether it fixes the issue, but V4A still isn't working for Bluetooth

**Comment by ShadySquirrel** [comment]
You can always use edit button :D

Thing is, I could probably do something about SEPolicy issues, if I gather enough logs, but I can't do anything for bluetooth support because that requires library-level changes, which I can't provide - only V4A authors can. I'm just distributing a convenient way for users to flash V4A.

**Comment by SaamyoHalder** [comment]
Oh okay. Thanks for the help 😀

Do you know where I should ask for assistance?

**Comment by ShadySquirrel** [comment]
For Bluetooth issues with v4a, either your device forums or V4A official thread on XDA
