### ISSUE TITLE
Duplicating entries when updating module from previous verdion

### ISSUE THREAD

**Issue by k0u5h1k** [ShadySquirrel/ViPER4Android#21]
As per script, ur module copy and edit old audio_effects.conf file and add v4a lib path file.. So when updating from a previous module version, the audio_effects.conf file gets duplicate entries of v4a lib path..
![screenshot_20180122-003212](https://user-images.githubusercontent.com/35483317/35197840-ce48640e-ff0b-11e7-96ac-590b52933065.png)

**Comment by ShadySquirrel** [comment]
Yeah, that glitches sometimes on some ROMs, usually doesn't (for example hasn't occurred on mine so far). Trying to find a better way than 'grep v4a' to check for entries for a bit now.

**Comment by ShadySquirrel** [comment]
Started working on this. Complicates installation scrip a bit (more than 50 lines added so far) but it should prevent stuff like this. I'll need testers.

**Comment by k0u5h1k** [comment]
I will be busy for some days.. from 28th jan I will be free to test all ur changes bro

**Comment by ShadySquirrel** [comment]
Take your time, I'll test it on my devices for a while, that's for sure.

**Comment by Zackptg5** [comment]
You could use sed to search for it and patch if non existent:
test ! $(sed -n "/v4a_fx {/,/}/p" $cfg_file) && sed -i "s/^libraries {/libraries {\n  v4a_fx {\n    path system\/lib\/soundfx\/libv4a_fx_ics.so\n  }/g" $cfg_file

Same concept for effect entry

Or you could just delete any existing v4a entries before adding your own:
sed -i "/v4a_fx {/,/}/d" $cfg_file

**Comment by ShadySquirrel** [comment]
And here you see a guy who learned regular expressions and sed.

I hate sed and sh, TBH. If there is was a way I could make this script run in python, I would do that.

My current implementation is bit different ATM: I'm checking for number of entries via `grep -we` and finding out which one is missing, if some entries are already there. But I really like your oneliner, will just have to adjust it for new xml format, too.

**Comment by Zackptg5** [comment]
I hate sh and sed too, I want to learn awk but never bothered since it's not a standard Android binary :/

Here's how you would want it for XML files (it's a bit easier minus the escaped internal quotes since each entry is a 1 liner):
sed -i "/v4afx/d" $cfg_file
sed -i "/<libraries>/ a\        <library name=\"v4a_fx\" path=\"libv4a_fx_ics.so\"\/>" $cfg_file

**Comment by ShadySquirrel** [comment]
Does this take spaces and tabs into consideration?

You can see that I'm using spaced/tabbed entries in my code:
```
sed -i 's/^    <libraries>/    <libraries>\n        <library name="v4a_fx" path="libv4a_fx_ics.so"\/>/g' $CFG
sed -i 's/^    <effects>/    <effects>\n        <effect name="v4a_standard_fx" library="v4a_fx" uuid="41d3c987-e6cf-11e3-a88a-11aba5d5c51b"\/>/g' $CFG
```
Because that's mostly the only way it worked on all devices I've tested.

**Comment by Zackptg5** [comment]
Yup, I try to keep the files neat looking  :)

**Comment by ShadySquirrel** [comment]
Nice. I think I can scrap my function right now, lol.

This is code I wrote so far:
```
# Requires 3 parameters:
# - $1 - original config name
# - $2 - original config path
# - $3 - config format (0 for plain, 1 for xml)
edit_config () {
    if [ $# -lt 3 ] || [ $# > 3 ]; then
	ui_print "/!\ Invalid function call!"
    else
	# count of entries.
	CNT=`grep -wc 'v4a_fx' $1`
	
	# files
	OLD_CFG=$1
	CFG_PATH=$2
	XML=$3
	NEW_CFG="$CFG_PATH/$OLD_CFG"
	
	ui_print "* Editing effects configuration file in $1"
	
	# if there are exactly zero v4a_fx entries, it's a full install.
	if [ $CNT -eq 0]; then
	    ui_print "=> No traces of previous V4A configuration found, configuring."
	    
	    # create $CFG_PATH only if it doesn't exist
	    if [ ! -d $CFG_PATH ]; then
		ui_print "=> Creating $CFG_PATH overlay..."
		mkdir -p $CFG_PATH 2>/dev/null
	    fi
	    
	    ui_print "=> Copying old configuration..."
	    cp -af $OLD_CFG $NEW_CFG 2>/dev/null
	    
	    ui_print "=> Modifying old configuration"
	    # depending on the config format, different sed lines.
	    if [ $XML -eq 0 ]; then
		ui_print '=> Using plain config file'
		sed -i 's/^libraries {/libraries {\n  v4a_fx {\n    path \/system\/lib\/soundfx\/libv4a_fx_ics.so\n  }/g' $NEW_CFG
		sed -i 's/^effects {/effects {\n  v4a_standard_fx {\n    library v4a_fx\n    uuid 41d3c987-e6cf-11e3-a88a-11aba5d5c51b\n  }/g' $NEW_CFG
	    elif [ $XML -eq 1 ]; then
		ui_print "Using new XML format"
		sed -i 's/^    <libraries>/    <libraries>\n        <library name="v4a_fx" path="libv4a_fx_ics.so"\/>/g' $CFG
		sed -i 's/^    <effects>/    <effects>\n        <effect name="v4a_standard_fx" library="v4a_fx" uuid="41d3c987-e6cf-11e3-a88a-11aba5d5c51b"\/>/g' $CFG
	    else
		ui_print "/!\ Unsupported config format!"
	    fi
	    ui_print "=> Finished!"
	    ui_print " "
	    
	elif [ $CNT -eq 1]; then
	    # this is partial configuration. We have to find where is missing what...
	    
	fi
    fi
	
}
```

**Comment by Zackptg5** [comment]
Oh wow, that's way more work than you need to do but it would work. I just do something like this:
`CFGS="${CFGS} $(find -L /system -type f -name "*audio_effects*.conf")"
CFGSXML="${CFGSXML} $(find -L /system -type f -name "*audio_effects*.xml")"

for FILE in ${CFGS}; do
  cp -f $FILE $MODPATH$FILE
  sed -i "/v4a_standard_fx {/,/}/d" $MODPATH$FILE
  sed -i "/v4a_fx {/,/}/d" $MODPATH$FILE
  sed -i "s/^effects {/effects {\n  v4a_standard_fx {\n    library v4a_fx\n    uuid 41d3c987-e6cf-11e3-a88a-11aba5d5c51b\n  }/g" $MODPATH$FILE
  sed -i "s/^libraries {/libraries {\n  v4a_fx {\n    path \/system\/lib\/soundfx\/libv4a_fx_ics.so\n  }/g" $$MODPATH$FILE
done
for FILE in ${CFGSXML}; do
  cp -f $FILE $MODPATH$FILE
  sed -i "/v4a_standard_fx/d" $MODPATH$FILE
  sed -i "/v4a_fx/d" $MODPATH$FILE
  sed -i "/<libraries>/ a\        <library name=\"v4a_fx\" path=\"libv4a_fx_ics.so\"\/>" $MODPATH$FILE
  sed -i "/<effects>/ a\        <effect name=\"v4a_standard_fx\" library=\"v4a_fx\" uuid=\"41d3c987-e6cf-11e3-a88a-11aba5d5c51b\"\/>" $MODPATH$FILE
done`

**Comment by ShadySquirrel** [comment]
Whoa!

Would you like to make a pull request with those changes? I'll make a master-next branch in a minute so you can fork that and implement that in config.sh, and I could give you proper credit.

Just make `$CFGS` and `$CFGSXML` a standard array where I should enter paths, because some devices don't follow that audio_effect.{conf,xml} naming routine.

**Comment by Zackptg5** [comment]
Sure! You can always add more items to the arrays (they're not really arrays, just space separated string because sh shell is garbage and doesn't support true arrays...) with this:
CFGS="${CFGS} new_file.xml"

**Comment by ShadySquirrel** [comment]
Let's call it an array, they like calling that an array :D (remembered what I had to do in PHP once, because of bad frontend implementation).

Branch is alive, feel free to fork and commit whenever you can!

Thank you!

**Comment by Zackptg5** [comment]
Done :)

**Comment by ShadySquirrel** [comment]
Thanks. I just had one suggestion, so if you can add that too and I'll merge it and start testing!

**Comment by Zackptg5** [comment]
Looks like this issue cane be closed now :)

**Comment by ShadySquirrel** [comment]
Just one thing I've found out, looks like Pixels aren't using /system/vendor, just /vendor, at least on stock. Searched though sources and haven't found a mention of /system/vendor symlink/mount.

What do you suggest here? Telling `find` to ignore symlinks and adding /vendor to search patterns or you have something better in mind?

**Comment by Zackptg5** [comment]
My bullhead has the same setup and it works fine. That's what I was saying before. 
For devices with a separate vendor partition, there's a seemingly empty file called 'vendor' in /system. This is the symlink and any commands in twrp will follow it fine (and obviously fine in bootmode too).
The -L flag in the find command tells it to follow the symlink.

**Comment by ShadySquirrel** [comment]
One more thing I didn't know about (that preexisting symlink). My previous device used a bind mount for that if I remember correctly, and haven't started building for new one (which should have separate vendor) yet.

Thanks again! I'm adding some commentary now, and I'll create & upload new zip for people to test.

**Comment by k0u5h1k** [comment]
I will be free to test ur changes tomorrow..

**Comment by ShadySquirrel** [comment]
For everyone interested, I've published both materialized and standard version installers [here](https://github.com/ShadySquirrel/ViPER4Android/releases/tag/v6.0).

Flash it, test it, report issues if any (ofc in separate thread, I'll close this one). I'll give it a week? or so before pushing to Magisk repo.

Thanks to everyone involved!

**Comment by k0u5h1k** [comment]
Yes that version is working perfectly..
