### ISSUE TITLE
Drivers are not Installing 

### ISSUE THREAD

**Issue by ZenderXCage** [ShadySquirrel/ViPER4Android#25]
I tried Many Times But Its Failed on My Yureka Plus please Fix This

**Comment by ZenderXCage** [comment]
Using Nitrogen Os New Build 23 - 1 - 18

**Comment by Zackptg5** [comment]
Logs?

**Comment by ZenderXCage** [comment]
I don't have Logs Man😏😏

**Comment by ZenderXCage** [comment]
m using Magisk Installation

**Comment by ShadySquirrel** [comment]
You know how they say, "logs or it didn't happen".

So, if you want help: Logcat and audio effects config files is a bare minimum.

**Comment by ZenderXCage** [comment]
How shoud i do this? get Logs

**Comment by ShadySquirrel** [comment]
This is exactly reminding me why I've stopped publishing stuff on XDA. 

There are tons of tutorials, don't be lazy, Google it a bit.

**Comment by ZenderXCage** [comment]
m new to viperfx So should i expect any help from You??

**Comment by Zackptg5** [comment]
@ZenderXCage 
How to logcat: https://forum.xda-developers.com/showthread.php?t=1726238
To get magisk log: go into magisk manager -> logs => hit the save button

@ShadySquirrel 
It's been getting worse there too. It's becoming less and less a developers forum

**Comment by ShadySquirrel** [comment]
@ZenderXCage you can get help about my module, but not basic stuff every android "power" user should know.

@Zackptg5 so many people just coming with "doesn't work, fix it now" but when you ask for logs and testing, nobody has a clue. Reason why I decided to use github for issue tracking/support...  That and reasoning that people actually using it know how to do error reports.
