### ISSUE TITLE
Pixel 2 8.1 io driver 

### ISSUE THREAD

**Issue by dviree** [ShadySquirrel/ViPER4Android#27]
[2018-01-27_21.41-bajs.zip](https://github.com/ShadySquirrel/ViPER4Android/files/1670462/2018-01-27_21.41-bajs.zip)
[magisk_log_20180127_213157.log]
![screenshot_20180127-214528](https://user-images.githubusercontent.com/33899343/35475729-84615446-03ab-11e8-9be3-8f239503602f.png)
(https://github.com/ShadySquirrel/ViPER4Android/files/1670456/magisk_log_20180127_213157.log)
Can't install drivers
[audio_effects.zip](https://github.com/ShadySquirrel/ViPER4Android/files/1670465/audio_effects.zip)

**Comment by dviree** [comment]
[
[]([]([]([Log_2018-01-27_21-30-30.txt](https://github.com/ShadySquirrel/ViPER4Android/files/1670452/Log_2018-01-27_21-30-30.txt))))
](url)

**Comment by dviree** [comment]
[Log_2018-01-27_21-30-30.txt](https://github.com/ShadySquirrel/ViPER4Android/files/1670454/Log_2018-01-27_21-30-30.txt)

**Comment by dviree** [comment]
Can't upload my audio conf [file[](url)](url)

**Comment by dviree** [comment]
![screenshot_20180127-213742](https://user-images.githubusercontent.com/33899343/35475619-5905bebe-03aa-11e8-940c-fa071cbe1214.png)
![screenshot_20180127-213717](https://user-images.githubusercontent.com/33899343/35475613-4d04cb28-03aa-11e8-8939-7362dfccb313.png)

**Comment by ShadySquirrel** [comment]
There should be one more audio effect configuration file on 8.1. Check /system/vendor/etc or /vendor/etc.

Also, please try with latest module (v6, available on Github, under releases).

And please, don't post images, at least not full-sized ones, and try to keep everything in one comment, just to make this easier to read.

**Comment by dviree** [comment]
There's only one .conf file on system/etc
There are more on system/vendor/etc but it's in 
.xml
Yeah sure im not really accustomed to GitHub I'll fix the images for next time

**Comment by dviree** [comment]
Is it okay for you to link me the zip? I'm really new to girhub

**Comment by ShadySquirrel** [comment]
Yeah, that file is still valid, Oreo is using new config format - XML. 

I'm guessing that v5.2 hasn't detected the file, and hasn't edited it because that /system/vendor/etc path was added later. Releases can be found [here](https://github.com/ShadySquirrel/ViPER4Android/releases)

**Comment by dviree** [comment]
Alright so it's still the same problem 
I've attached everything I think you can use. 
[git.zip](https://github.com/ShadySquirrel/ViPER4Android/files/1670498/git.zip)
don't kill me if I attached too many things

**Comment by ShadySquirrel** [comment]
Everything is fine with configs... I'll need Magisk log, installation log too. Also, if you could grab a logcat (with `adb logcat -b all`) while running V4A in both permissive and enforcing mode.

**Comment by dviree** [comment]
Here ya go
[git2.zip](https://github.com/ShadySquirrel/ViPER4Android/files/1670504/git2.zip)

**Comment by dviree** [comment]
Any update ? What's happening

**Comment by ShadySquirrel** [comment]
Sorry, bit busy today, I'll take a look later

**Comment by ShadySquirrel** [comment]
Can you list me the contents from `/system/lib/soundfx`?

It seems that you have same problem as described in #26 (Magisk isn't mounting my module's paths).

Can you try removing other modules and running only with mine?

**Comment by karanrom** [comment]
Hi.. Even I'm facing the above problem..not able to install viper5.2 even after removing other modules..Oreo 8.1.. Aokp ROM.

**Comment by karanrom** [comment]
I didnt try older version(2.3.4)

On 29-Jan-2018 10:30 PM, "DEMONVoz" <notifications@github.com> wrote:

i have the same problem. have you tried older version of magisk?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/ShadySquirrel/ViPER4Android/issues/27#issuecomment-361312388>,
or mute the thread

**Comment by belldant** [comment]
same issue here.. im at android 8.0.. can't installed the driver..

**Comment by belldant** [comment]
nevermind, it worked great now.. just neet to remove the AML Modules.. thanks man..

**Comment by ShadySquirrel** [comment]
And my question is still left unanswered....

**Comment by ShadySquirrel** [comment]
Closed due to inactivity.
