### ISSUE TITLE
Install/update the driver issue

### ISSUE THREAD

**Issue by sixthpr1m3** [ShadySquirrel/ViPER4Android#28]
I have been using this module for a long time. Today I removed the module completely(v5.0), tried installing Dolby magisk module which unfortunately didn't work, so I removed that module, installed the new V4A (v5.2) module. Since then it's asking me to install/update the driver. I tried removing the v5.2 and installed v5.0. Still asking for driver install/update.
ROM: AEX 4.6 (7.1.2)
Magisk Version:15.3
No other audio mods installed.

[magisk_log_20180202_155816.log](https://github.com/ShadySquirrel/ViPER4Android/files/1688962/magisk_log_20180202_155816.log)
[install_log_20180202_152258.log](https://github.com/ShadySquirrel/ViPER4Android/files/1688963/install_log_20180202_152258.log)
[audio_effects.conf.txt](https://github.com/ShadySquirrel/ViPER4Android/files/1688964/audio_effects.conf.txt)

**Comment by ShadySquirrel** [comment]
Let me guess, you haven't rebooted between module installations?

```
01-01 06:06:58.316   446   465 I Magisk  : bind_mount: /vendor/etc/audio_effects.conf.bak
01-01 06:06:58.316   446   465 I Magisk  : bind_mount: /vendor/etc/audio_effects.conf
01-01 06:06:58.316   446   465 I Magisk  : bind_mount: /vendor/etc/audio_output_policy.conf.bak
01-01 06:06:58.316   446   465 I Magisk  : bind_mount: /vendor/etc/audio_output_policy.conf
```
And you've installed my module first and then removed Dolby... or something in between the lines. Because I'm not creating .bak files, especially not within my module - it just makes a copy of file during setup, edits it, and stores it in it's module folder for auto mounting, so I'm thinking that those config files weren't touched by my installer, or config touched by my installer were removed by something other.

Also, you've kept AML installed even I explicitely said that this module has no such requirement:
```
I'd suggest removing my module (and any other module which is messing with audio_effects.conf) completely, rebooting then trying with [v6 from Releases](https://github.com/ShadySquirrel/ViPER4Android/releases/tag/v6.0)

**Comment by sixthpr1m3** [comment]
Thank you for a quick and detailed reply. Since I was trying to install different audio mods, I made sure I rebooted after each uninstallation and installation. But there were two weird instances between all these reboots:
1) once the phone screen turned off soon after the boot animation, just the notification LED lits up(this happens randomly with my phone, so usually I force it to reboot with hardware key combos)
2) once the phone booted normally, but when I checked the magisk module section all my modules have disappeared. I rebooted the phone and the modules were all back.

I think AML was installed by the Dolby module. Now I suspect that the Dolby module uninstallation got messed up when that phone was stuck at the boot. Shall I try installing the Dolby module and try uninstalling it again to completely remove it?

And do you recommend me to restore the **audio_effects.conf.bak** & **audio_output_policy.conf.bak** or leave it as it is? Added current files and .bak files for comparison

[audio_output_policy.conf.txt](https://github.com/ShadySquirrel/ViPER4Android/files/1689179/audio_output_policy.conf.txt)
[audio_effects.conf.txt](https://github.com/ShadySquirrel/ViPER4Android/files/1689180/audio_effects.conf.txt)
[audio_effects.conf.bak.txt](https://github.com/ShadySquirrel/ViPER4Android/files/1689183/audio_effects.conf.bak.txt)
[audio_output_policy.conf.bak.txt](https://github.com/ShadySquirrel/ViPER4Android/files/1689184/audio_output_policy.conf.bak.txt)

**Comment by ShadySquirrel** [comment]
No, just make sure you've removed all audio related modules you have before installing mine, original files should get restored.

If you can't remove them from Manager, try from recovery (I think that Magisk recovery mount is still working properly, saved my ass few times). 

My module will find all necessary config files, copy them and modify from scratch so you don't need to change anything.

P.S. That notification light freeze is typical for kernel crash or init issue during boot-up, you may want to grab panic logs for that and provide to the maintainer, if it isn't happening on stock.

**Comment by sixthpr1m3** [comment]
I have been thinking about dirty/clean flashing my ROM again for past few days as I have some other issues which started long back when I flashed some zip through TWRP and I now don't remember what it was for.

And thank you so much for this module and bonus knowledge about the frozen notification LED.  Cheers

**Comment by ShadySquirrel** [comment]
You're welcome :) Shouldn't close the issue before you can confirm everything is working, though :D

Cheers.

**Comment by sixthpr1m3** [comment]
I'm sorry, as per the info provided by you, I was pretty sure that I messed it up and it was not an issue with the module. So I thought of closing it.

I flashed the ROM again and just now installed your module and it works like charm.

Again I'm really sorry for the trouble. You were really helpful.

If possible could you please suggest or send me some good effect(preferably bass) profiles for Viper4Android?

**Comment by ShadySquirrel** [comment]
Nah it doesn't bother me, just saying :) TBH, I don't like when number next to 'Issues' is different of zero, but well...

I can't help you there much, I'm using same configuration for my earphones and headphones for more than 5 years now (basically I haven't changed headphones for that long) and my definition of good sound is probably different. You can try playing with Viper Bass and dynamic system, depending on the other settings and your headphones, it will give you a nice kick. I can give you my default configuration for Panasonic HJE125 if that means something to you.

**Comment by sixthpr1m3** [comment]
I think, I will take some time and figure out some good effects for my earphones as per your suggestion.
Peace out :)
