### ISSUE TITLE
module v6 driver abnormal

### ISSUE THREAD

**Issue by exodius48** [ShadySquirrel/ViPER4Android#29]
- module v6, magisk 15.3 stable
- phone model xiaomi Mi A1, Android oreo OS 8.0.0
- Installed module: DolbyAtmos orero https://forum.xda-developers.com/android/software/app-dolby-atmos-axon-7-oreo-port-t3740508 , google lens enabler, ios11.1 emoji, magisk manager for recovery, gcam fix oreo, sonyapps enabler, sony-music4magisk, sysconfig patcher, unified host adblock, viper4android fx for magisk v15, xposed framework sdk26
- No other sound mod installed, only dolby oreo by guitardedhero that installed
- Screenshot: https://i.imgur.com/IIwE2wP.png Logs: https://sendit.cloud/kojs8oj09flc
- Audio effect: https://sendit.cloud/k13x7l5e9g0o

After instal from magisk app, module do]es not work, driver status abnormal.

**Comment by ShadySquirrel** [comment]
Remove the dolby module, reboot, reinstall mine and try again. I'll take a look at logs later, when I get to my computer.

**Comment by ShadySquirrel** [comment]
I took a look at logs - that Dolby module is wiping my V4A configuration completely and overriding complete soundfx folder - there is no trace of V4A library existing, nor being mounted, nor a single trace of V4A entries in those config files.

You **will** have to remove Dolby, and reinstall my module if you want to use it.

**Comment by exodius48** [comment]
OK. I only disabled dolby not removed it, and it works https://i.imgur.com/RdFpTD7.png
Is there any fix to run your v4a and dolby together?

**Comment by ShadySquirrel** [comment]
Yes, use AML version of V4A, not this one. 

I tend to keep things minimalistic and to be honest with you, I see no point, or sound quality increase with multiple sound mods/libraries installed, so that would never be supported.

**Comment by exodius48** [comment]
OK bro, problem solved.
