### ISSUE TITLE
can't install v4a magisk v6

### ISSUE THREAD

**Issue by Nazukii** [ShadySquirrel/ViPER4Android#31]
install log says:

- Copying zip to temp directory
- Installing ViPER4Android_FX_for_Magisk_v15-v6.zip
- Mounting /system, /vendor
Archive:  /data/user/0/com.topjohnwu.magisk/cache/install.zip
update-binary: /dev/tmp/install/config.sh: line 106: syntax error: unexpected "(" (expecting "}")
  inflating: common/file_contexts_image
  inflating: common/post-fs-data.sh
  inflating: common/service.sh
  inflating: common/system.prop
  inflating: config.sh
  inflating: module.prop
Failed!
! Installation failed

previous versions were working fine

**Comment by ShadySquirrel** [comment]
From where are you installing that? No such issue on my device.

**Comment by ShadySquirrel** [comment]
Also, [you know the drill](https://github.com/ShadySquirrel/ViPER4Android#support)

**Comment by Nazukii** [comment]
[things.zip](https://github.com/ShadySquirrel/ViPER4Android/files/1699117/things.zip)

latest Magisk 15.3
Redmi Note 3 Pro - 8.1 Oreo Nitrogen OS
List as screenshot
no sound mods (that i'm aware of)
could only find audio_effects.conf (does the xml have a different name, not just ending?)

**Comment by ShadySquirrel** [comment]
Full logs are still missing...

**Comment by Nazukii** [comment]
magisk log here, no time for logcat right now

[install_log_20180206_133214.log](https://github.com/ShadySquirrel/ViPER4Android/files/1699146/install_log_20180206_133214.log)

**Comment by ShadySquirrel** [comment]
Funny thing is, it shouldn't fail for a syntax error.

Even funnier thing is that same zip from Magisk repo is working flawlessly on my device, with no errors.

So, either is shell busted on the ROM you're using, either something else is going on.

**Comment by Nazukii** [comment]
can I do anything? I also tried to flash the older + materialized version, which works at first glance but V4A App keeps on crashing (in the background), which makes the phone pretty much unusable... any idea?

**Comment by ShadySquirrel** [comment]
Have you tried v6 from my releases?

Give me a few to rework that code and I'll upload something for you to test.

**Comment by Nazukii** [comment]
v6 (rev10) gives me the install error. Then I tried v5.2 or rev8. Which allows installation, but V4A App keeps crashing. Like non-stop and giving me notifications about the crashes

**Comment by Nazukii** [comment]
which makes the phone unusable until i disable the app and make it force stop

**Comment by ShadySquirrel** [comment]
[Try this one](https://github.com/ShadySquirrel/ViPER4Android/files/1700236/viper4android-v6-Magisk-1500.zip)

**Comment by Nazukii** [comment]
seems to be working just fine :)
thank you very much.

**Comment by ShadySquirrel** [comment]
Can you test the reuploaded file? I had a code derp there.

**Comment by Nazukii** [comment]
working fine also :)

**Comment by ShadySquirrel** [comment]
Thank you :D I'll push the changes to official repo soon.

Thanks for the feedback! Closing and marking as solved.

**Comment by Nazukii** [comment]
thanks for the help!
