### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by Zackptg5** [ShadySquirrel/ViPER4Android#32]
With the new aml, this module (along with any other v4a module) is compatible with new aml. You can also use this mod with others if using new aml

**Comment by ShadySquirrel** [comment]
I completely forgot about that. I'll edit that as soon as I have free time. Thanks for reminding me!

**Comment by ShadySquirrel** [comment]
How does this sound:

> 2. **This module is compatible with *new* Audio Mod library**. Combining with with other audio mods, *without AML* will produce issues. Consider that before reporting.

**Comment by Zackptg5** [comment]
Sounds good to me, thanks!

**Comment by ShadySquirrel** [comment]
OK, done. Thanks again!

Closing this issue.
