### ISSUE TITLE
Musicfx is not getting blacklisted

### ISSUE THREAD

**Issue by k0u5h1k** [ShadySquirrel/ViPER4Android#33]
After the latest update musicfx is not getting blacklisted on my mi a1

**Comment by ShadySquirrel** [comment]
You're forgetting something.

**Comment by k0u5h1k** [comment]
When installing viper, previously it used to say that musicfx found and blacklisted but after the latest update, it no more shows that.. and also musicfx is not getting replaced by magisk way..

**Comment by ShadySquirrel** [comment]
There is no way I can replicate this, because script works with my devices, and you haven't provided any logs for 10 days now...

**Comment by k0u5h1k** [comment]
Oh I am sorry for the logs.. Now I understand what did you mean by "You're forgetting something.".. will upload the logs soon..

**Comment by k0u5h1k** [comment]
Do you want anything else?

**Comment by ShadySquirrel** [comment]
No, I'll take a look when I finish some stuff in next few days. I hope that module is working ok.

**Comment by ShadySquirrel** [comment]
Can't replicate this on my devices, logs say nothing specific
