### ISSUE TITLE
Does LDAC work with V4A

### ISSUE THREAD

**Issue by curiozity345** [ShadySquirrel/ViPER4Android#35]
I have 2 indentical 6P'S running Nitrogen OS with 8.1 and Elemental X. One has APTX headphones and works well with V4A. But the other does not work when I have LDAC enabled with my Sony bluetooth speaker, but works fine when I disable HD audio in Bluetooth settings. My question is...does LDAC work with V4A? If so, I'm happy to send logs etc to troubleshoot.

**Comment by ShadySquirrel** [comment]
I'm pretty sure it doesn't, it was already discussed on XDA thread.

It probably can be fixed, but that would be a job for library developer, not for me, I'm just providing a convenient way to install it.

**Comment by curiozity345** [comment]
Yes, you have provided a fantastic way to install it. Thanks heaps for your work. Maybe if and when a official Oreo update comes from the devs, APTX will work.

**Comment by ShadySquirrel** [comment]
We can only hope :) I'm planning a device change and move to wireless headphones, so it would be nice to get APTX working... but unfortunately, release cycle seems to be 'only when we have to', and library isn't open-sourced so... not much help from enthusiasts.
