### ISSUE TITLE
Need to install/update the driver

### ISSUE THREAD

**Issue by Primokorn** [ShadySquirrel/ViPER4Android#36]
Hi,
Your module was working fine until I update my custom ROM OmniROM. Now I have this message:
![screenshot_viper4android_fx_20180214-161057](https://user-images.githubusercontent.com/5938828/36244514-c3c5f400-1226-11e8-920b-df3ef7316745.png)

Module version: 6.0.1
Magisk version: 15.3
Phone: OnePlus 3T, Android 8.1.0, OmniROM, stock kernel set to Enforcing.
No other sound installed
Log:
[Log_2018-02-14_16-19-26.txt](https://github.com/ShadySquirrel/ViPER4Android/files/1724581/Log_2018-02-14_16-19-26.txt)
`02-14 16:19:18.511  3342 14508 I ViPER4Android: ViPER4Android engine not found
02-14 16:19:18.511  3342 14508 I ViPER4Android: Android audio effect engine reports the v4a driver is not usable`

Here are my audio_effects.conf files:
[audio_effects.zip](https://github.com/ShadySquirrel/ViPER4Android/files/1726651/audio_effects.zip)

I tried to open V4A app with SELinux set to permissive but it didn't help.

Thank you.

**Comment by ShadySquirrel** [comment]
I'll need magisk logs and contents of `/magisk/viper4android` to compare outputs.

According to this, module installation went wonky, but just to be sure because there are tons of issues with Magisk and devices using F2FS or encryption.

**Comment by Primokorn** [comment]
[Magisk log](https://primokorn-drive.mycozy.cloud/public?sharecode=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJzaGFyZSIsImlhdCI6MTUxODcwMzA1NiwiaXNzIjoicHJpbW9rb3JuLm15Y296eS5jbG91ZCIsInN1YiI6ImVtYWlsIn0.ZYRG3JGh8n5j_uCNLZo0LHt76QZuHkH1WnVtnu8mL-Lz9yLxl7S4qsP77mufEWofFjmDnnEz5yYXeU6O0gc64A&id=cc247533fe53612774dddc27a5893edc)
[Contents of /magisk/viper4android](https://primokorn-drive.mycozy.cloud/public?sharecode=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJzaGFyZSIsImlhdCI6MTUxODcwMzA4NSwiaXNzIjoicHJpbW9rb3JuLm15Y296eS5jbG91ZCIsInN1YiI6ImVtYWlsIn0.IIkC4HVAcAP75KzXOSOyDWsLy8BnuefpWg3QnPHHM-bgkbD22DOnF82NJ3CCZrq7nFtb4c2U-9AFLHm9vJHL_A&id=cc247533fe53612774dddc27a5894936)

My /data partition uses ext4 and it's encrypted.

**Comment by ShadySquirrel** [comment]
Problem is repeating and I have no solution for it - Magisk simply doesn't mount paths properly. Sometimes it doesn't mount configuration files, sometimes it didn't mount library files.

I'm guessing you had a reboot before this and previous logs? In previous logs, audio configuration wasn't mounted, now V4A library...

I've noticed something strange there, too.. For some reason Magisk remounts whole /system/lib, insted it needs to remount just /system/lib/audiofx for my module... Which modules do you have there?

**Comment by Primokorn** [comment]
OK, thanks.
Yes I rebooted to restore a nandroid backup, to flash your module,...
Your V4A Magisk module is the only one I have installed.

Maybe @topjohnwu could have a look.

**Comment by ShadySquirrel** [comment]
Someone already reported that on XDA; I'm trying to investigate a bit more and find a possible fix but most things in common so far were f2fs data and encryption. And for some weird reason mostly OnePlus users were hit by this.

I'd see to encrypt my phone in next few days and see if this is behavior I'm having, too. Last encryption try failed miserably because something went wonky and I was left with nearly broken system...

**Comment by Primokorn** [comment]
FWIW I get V4A working with [this module](https://forum.xda-developers.com/apps/magisk/module-viper4android-fx-2-5-0-5-t3577058/post75589364#post75589364) and after modifying [this file](https://forum.xda-developers.com/showpost.php?p=75589332&postcount=2086).
