### ISSUE TITLE
How to change app color (materialized)

### ISSUE THREAD

**Issue by keeganjk** [ShadySquirrel/ViPER4Android#37]
I'm using the Materialized version of this app with Magisk v16 (sound is awesome!). I've used the FreedomOS ROM, which has Viper4ARISE, which is basically the same thing. However, it's black and red instead of black and purple. How do I change the app interface to red?

**Comment by ShadySquirrel** [comment]
Change the app for one with theme/Substratum support. This module is using standard materialized app, same as one provided via XDA labs.

**Comment by keeganjk** [comment]
@ShadySquirrel Substratum suggests not to use Substratum in new versions of Android. Are there any alternatives?

**Comment by keeganjk** [comment]
What do you mean extracting the app and installing it? How would that be any different?

**Comment by ShadySquirrel** [comment]
By extracting and installing the app I mean that: grab Viper4ARISE flashable, find the Viper4Android apk there, get it from the zip and install it manually :)

**Comment by keeganjk** [comment]
Found the APK but don't know what to modify.

**Comment by ShadySquirrel** [comment]
Just install it on your device.

**Comment by keeganjk** [comment]
But it's the *exact same thing that's already installed...* Wait– oh. Where do I get the V4ARISE zip?

**Comment by keeganjk** [comment]
I tried to install it, but all it did was replace the icon of the original app...

**Comment by keeganjk** [comment]
nvm. rebooted and it looks gr8

**Comment by keeganjk** [comment]
Here's the link for anyone who may need it (all black version): https://goo.gl/jD3RLx
