### ISSUE TITLE
Force close on Nexus 6P

### ISSUE THREAD

**Issue by tengoku-sama** [ShadySquirrel/ViPER4Android#4]
I recently updated the module from Magisk and now I get endless ViPER4Android FX has stopped errors on reboot. I managed to uninstall the module and got it to stop and tried reinstalling but the force close error persists.

Is there anything I could try to resolve it?

Nexus 6P, stock 8.0, Franco kernel

**Comment by Youxikong** [comment]
The same as mine.

**Comment by ShadySquirrel** [comment]
V4A doesn't support O yet. That's not a problem with module.
