### ISSUE TITLE
Magisk 16.4 and V4A 6.1 - Driver status: Abnormal

### ISSUE THREAD

**Issue by fastleo63** [ShadySquirrel/ViPER4Android#41]
As in subject.
I tried to set SELinux to permissive too, but no avail.
Uninstalling 6.1 and installing previous 6.0.1 solved the problem.
OnePlus One 64 GB, TugaPower ROM N58 (LineageOS 14.1 - Android 7.1.2r36).

**Comment by ShadySquirrel** [comment]
Does Magisk's late_start work on your device? Only change is sepolicy injection move from post-fs to late_start

**Comment by Mipirakas** [comment]
Same here on my oneplus 5 on stock 8.1 rom. How to check if it's compatibel with lae_start?

**Comment by ShadySquirrel** [comment]
It should be. His device is on kernel 3.4 which isn't officially supported by Magisk and probably lacks some of patches it requires (Magisk officially supports 3.8.x+).

**Comment by Mipirakas** [comment]
I think you forgot to set LATESTARTSERVICE=true and POSTFSDATA=false in config.sh?

**Comment by ShadySquirrel** [comment]
And I'm wondering why it's working on my phones... You're right, I forgot to commit that change. Sh**.

Added, committed, pushed.

**Comment by Mipirakas** [comment]
Thanks, all working now!!

**Comment by ShadySquirrel** [comment]
@fastleo63 is this solved for you now?

**Comment by fastleo63** [comment]
Yes! Today I installed ViPER4Android 6.1.1, that solved the abnormal driver status.
Thanks,
Leonardo.

Il giorno 8 mag 2018, 18:43, alle ore 18:43, Shady Squirrel <notifications@github.com> ha scritto:
