### ISSUE TITLE
Driver installation issue

### ISSUE THREAD

**Issue by paradox-R** [ShadySquirrel/ViPER4Android#46]
Is this even active?
There's this driver installation issue that started just after recent update, it was working just fine till then. Can anyone help or is anyone listening?

**Comment by ShadySquirrel** [comment]
Haha, this one is long abandoned (from [README](https://github.com/ShadySquirrel/ViPER4Android#abandoned-viper4android-magisk-module)), and Magisk recently changed module template so I guess this is totally obsolete now...
