### ISSUE TITLE
Processing fails at certain situations

### ISSUE THREAD

**Issue by abhishekabhi789** [ShadySquirrel/ViPER4Android#47]
I've to open V4A FX (v2.7.1.0)  first,  then music player, in order to make "Processing= Yes" . (V4A isn't process the music automatically like system Audio FX)
When force closed V4A, I've to  close the music player, then launch V4A, and then again  music player, and then come back to check whether it is processing. If It shows "Processing=No" then again I've to close both V4A and music player.
Also, whenever it works, if I turn of 'master limit' it stops working. Then I need to do the above procedure again.
I've tested different V4A modules from Magisk (19.3) and all of them have the same issue.
I'm using redmi note 4 (mido) with Havoc-OS (Android 9)
Disabled system audio FX. Also tested with and without busybox from Magisk. Using Poweramp and ES File Explore media player.

**Comment by ShadySquirrel** [comment]
First thing first - this module is abandoned for a year now, and doesn't support newer Magisk since it's using 1500 module template.
Second thing - back when this was activelly maintained, Android 9 was quite not a thing so...
I'm closing this.
