### ISSUE TITLE
App crashes on 8.0+ constantly

### ISSUE THREAD

**Issue by sandrosdj** [ShadySquirrel/ViPER4Android#7]
The module worked fine on 8.0 before the last 2 updates.
Currently the application crashes until the system automatically do a factory reset.

//This isn't really an issue since you haven't mentioned support for 8.0+, but it was working fine before.//

**Comment by sandrosdj** [comment]
PS.: Anyone who has a copy from 2 updates before, I'd like to ask you to send it to me.

**Comment by ShadySquirrel** [comment]
Check [#3](https://github.com/ShadySquirrel/ViPER4Android/issues/3)
