### ISSUE TITLE
Processing error

### ISSUE THREAD

**Issue by pikatchu2k3** [ShadySquirrel/ViPER4Android#8]
I am no more able to use viper4android. 

This happened after a clean rom flashing process. 

Magisk version 14.3
Magisk manager version 5.4.0
Using latest module

Driver status:
Driver Version: 2.5.0.4
NEON Enabled: Yes
Enabled: Yes
Status: Normal
Audio Format: Supported
Processing: No
Sampling Rate: 48000

The difference to my previous config is just an update on my rom to the newest version (21.10.17 updated to 26.10.17)

I tried to collect some logs for you.

Device Axon 7
Resurrection remix 7.1.2 @26.10.17 build
Stock kernel
Viper4android doesn't work on normal or compatible mode
Uninstalled audio fx
Magisk 14.3 (tried also deactivating other modules)

Used modules:
Greenify4magiskv3.8.2
Injected YouTube background black v12.42.59

Error logs, ksmeg
https://www.sendspace.com/file/djlk0y

**Comment by ShadySquirrel** [comment]
Can't open dmesg, but other logs look okay, sepolicy and audio effects configuration is okay. It looks like it's some change in ROM or device config which triggered this issue. Can you find me a more up-to-date changelog for RR? Last info I've found is from september, and your build is more recent (october)

Two more things: have you tried disabling/reenabling effects in V4A app during playback, is there any change? Can you try with materialized module variant? It may be something with V4A app, happened to me after previous LOS update. P.S. backup your V4A profiles before any changes.

**Comment by pikatchu2k3** [comment]
I tried the dmseg log again. Opening on Smartphone takes a bit longer. Opening it with HTML Reader is working fast. On PC there are no problems open dmseg log.

Meanwhile I had a random reboot (again) and I decided to install official Lineage OS ROM. Interestingly there is the same problem!
I did try disabling/reenabling effects with no noticable effect on any setting.
Materialized version will be checked later.

**Comment by ShadySquirrel** [comment]
'cat' to the rescue, text editors didn't like your encoding.
Seeing your kmesg, it seems that there is a bunch of kernel crashes on your device. RR is probably just mirroring LOS device and kernel files, so I'd search for a culprit there. I'd suggest you to return back to previous build which was working properly, because only other reason you'd have issue like that with my module is presence of other audio effects/modules.

**Comment by pikatchu2k3** [comment]
Now I am on LOS.
Didn't had a reboot to since then, so I can't make another kmesg.

Did you take a look at the small error log? I created it with log level "errors" with matlog for the time I turned Viper4android on and off.


I also tried Magisk v14 without luck.

Do you think I have a software problem?
I try to find someone on Axon 7 forums, who is using your mod with never ROM builds.

**Comment by ShadySquirrel** [comment]
I saw that log, it's killing V4A app, that's why I told you to try with materialized module.

It could be that some changes in device/kernel tree are messing with you, because I'm on LOS (kiwi) and everything is just fine. Especially as you said that module worked fine before you've updated.
