### ISSUE TITLE
init.d requirement ?

### ISSUE THREAD

**Issue by adrenochrome25** [ShadySquirrel/ViPER4Android#9]
Hello,
i found your magisk module through magisk app in the download section, no xda support thread available ?
I'm using a Xiaomi Redmi4X running miui 8.3 (7.5.19) based on android 6.0.1, Magisk 14.0 with modules : "universal safetynet fix" (mandatory magiskhide on miui8), busybox 1.27.2, iYTB 3.0. SeLinux is set to "Enforcing" and set|getenforce is working ok.

Well... Driver status was always reporting "Enabled:false".
I was going to switch for another viper module when i saw in the new module readme that init.d was required. So I installed init.d through [init.d-injector-1.3](https://forum.xda-developers.com/android/software-hacking/mod-universal-init-d-injector-wip-t3692105) and i gave a last try to your module. Now it is working ok (enabled&processing) ! :)

As your module seems not to put anything into the init.d directory, i dont know if you simply forgot to add it to the requirement list or if it has something to do related to the other things the init.d installer changes into the system (sepolicy patches) ?

if you need any log or additional info to improve the potential compatibility of your module with other android variants, just ask me

**Comment by ShadySquirrel** [comment]
Um, all stuff you'd usually do with initd is done inside of [this](https://github.com/ShadySquirrel/ViPER4Android/blob/master-materialized/common/post-fs-data.sh) script, which is loaded by Magisk on boot and executed. No other hacks necessary, unless post-fs-data part of Magisk is broken for your firmware (which is probably the case here, seeing how all of those *MUI firmwares are oddballs, I have a device which came with EMUI, now is running LOS) or some of the modules is messing up (I'm tipping on busybox or USF, maybe even both).
